name: Build Docker Image

on:
  push:
    branches: [ main ]  # or master if that's your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t etabapp-image .

      - name: Save Docker image to file
        run: |
          docker save etabapp-image -o image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4  # ✅ use v4 here
        with:
          name: docker-image
          path: image.tar
